# Generated by Django 5.1 on 2025-02-02 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.task'),
        ),
    ]
