# Generated by Django 5.1 on 2025-02-02 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_task_task_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='management.task'),
        ),
    ]
